services:
  - type: web
    name: dnd-backend
    env: node
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    plan: free
    envVars:
      - key: NODE_VERSION
        value: 18.x
      - key: PORT
        value: 10000
      - key: MONGO_URI
        sync: false
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASS
        sync: false
      - key: EMAIL_HOST
        value: smtp.gmail.com
      - key: EMAIL_PORT
        value: 587
      - key: NODE_ENV
        value: production
    healthCheckPath: /api/health
    autoDeploy: true

  - type: static
    name: dnd-frontend
    rootDir: frontend
    buildCommand: npm install
    publishPath: public
    plan: free
    envVars:
      - key: NODE_VERSION
        value: 18.x
