services:
  - type: web
    name: dnd-backend
    env: node
    buildCommand: npm install
    startCommand: node backend/server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        sync: false
      - key: FRONTEND_URL
        sync: false
    healthCheckPath: /health
    autoDeploy: true
    rootDir: . 